README.md
=> README.md Change

.github/auto_assign.yml, .gitignore
[슬랙](https://2025springswppimo.slack.com/archives/C08HW204MRB/p1745484494592439)에서 공유드린 대로 새로 생성되는 pr에 제가 reviewer로 지정되어 빠르게 확인할 수 있도록 돕는 장치입니다
=> 태윤 자동 리뷰어로 설정하기

Assets/Prefabs/Commons.meta, Assets/Prefabs/Commons/IngameCanvas.prefab, Assets/Prefabs/Commons/IngameCanvas.prefab.meta, Assets/Scenes/SampleScene.unity
- Ingame Scene에서 사용할 UI Canvas를 Prefab화하였습니다.
- 추가된 IngameCanvas Prefab이 기존 UI 요소를 제대로 포함하고 있는지 확인해주시기 바랍니다.
- Stage Scene에 UI를 넣을 때 해당 Prefab을 인스턴스화하여 수정하지 말고 사용해주시기 바랍니다.
- UI 작업 시에는 해당 Prefab을 수정하시기 바랍니다.
=> [ETC] Add IngameCanvas prefab

Assets/Scenes/Stage1Scene.unity, Assets/Scenes/Stage1Scene.unity.meta
- 스테이지 1의 램프구간, 점프패드 구간 완료
- 연속 점프패드 구간 보완 필요
- 난이도가 적정한지
- 점프패드 키다운 계속 유지한채 진입하면 힘 적용 잘 안되는 것 같음.
=> [TASK-61] [TASK-62] Stage1 램프, 점프패드

Assets/Scenes/Stage4.unity, Assets/Scenes/Stage4.unity.meta, Assets/Scripts/Stage4.meta, Assets/Scripts/Stage4/ActivateButton.cs, Assets/Scripts/Stage4/ActivateButton.cs.meta, Assets/Scripts/Stage4/PredefinedBehaviour.cs, Assets/Scripts/Stage4/PredefinedBehaviour.cs.meta, Assets/Scripts/Stage4/SimpleMoveBehaviour.cs, Assets/Scripts/Stage4/SimpleMoveBehaviour.cs.meta, Assets/Scripts/Stage4/StopMoveBehaviour.cs, Assets/Scripts/Stage4/StopMoveBehaviour.cs.meta
- 스테이지 4 Scene을 추가했습니다.
- 스테이지 4에서 사용될 기믹용 스크립트를 추가했습니다.
- 추가된 스크립트는 변경 사항을 참고하시기 바랍니다.
- 스테이지 Scene이 필요한 오브젝트를 모두 포함하고 있는지
- 추가된 오브젝트가 잘 동작하는지
- Scene에 Managers, Player 등 기본 오브젝트 이외에 추가된 오브젝트는 없습니다.
=> [TASK-101] Add stage4 scene and scripts base

Assets/Prefabs/Commons/IngameCanvas.prefab, Assets/Scenes/SampleScene.unity, Assets/Scripts/Commons/CameraPivotController.cs, Assets/Scripts/Commons/PlayerController.cs, Assets/Scripts/Managers/GameManager.cs.meta, Assets/Scripts/Managers/PlayManager.cs, Assets/Scripts/SampleScene.meta, Assets/Scripts/SampleScene/SampleSceneGoalObject.cs, Assets/Scripts/SampleScene/SampleSceneGoalObject.cs.meta
- Scene 시작 시 유저 조작 제한, 1초 이후 조작 가능
- 스테이지 완료 시 유저 조작 제한, 5초 이후에 다음 Scene 불러오기
- 해당 기능이 제대로 작동하는지
- 콘솔에 Scene 시작 시 `Ready`, 1초 이후 `Playing`, 완료 시 `Finished` 메시지가 각각 표시
- 완료 5초 후 다음 Scene이 로드됨
- 딜레이 기간은 `PlayerManager.cs`에 `private const`로 지정되어 있습니다.
- 테스트 스크립트를 작성하여 Automated, Integrated test를 진행하려 했으나 ~~설정하다가 정신이 나가버려서~~ 테스트 작성의 오버헤드가 크다고 판단되어 Manual test로 수행하였습니다. 테스트를 위한 최소한의 오브젝트는 SampleScene에 추가되어 있습니다.
=> [TASK-130] Add PlayManager Start/Finish

Assets/Prefabs/Commons/IngameCanvas.prefab
- 기존에는 play ui가 0:00:00 이다가 게임이 시작하면 00:00:00으로 바뀌던데 이 부분이 좀 불편해서 수정했습니다
- 처음에 게임 시작하기 전에 원래 0:00:00으로 뜨셨을 텐데 00:00:00으로 바뀌었는지 확인 부탁드려요
- prefab 자체를 고친 거라 씬 작업자분들이 따로 하실 일은 없을 것 같음
위처럼 xx:xx:xx로 뜨는데 시작때만 0:00:00이던 것을 아래와 같이 수정함
=> [ETC] fixed common ui for same formatting

Assets/Scripts/Commons/NewPlayerControl.cs, Assets/Scripts/Obstacles/JumpPad.cs
- 점프패드 스크립트 옛날 PlayerController 바라보고 있던 버그 수정
=> JumpPad 스크립트 NewPlayerControl 업데이트 대응

Assets/Scenes/Stage1Scene.unity, Assets/Scripts/Obstacles/FinishPad.cs, Assets/Scripts/Obstacles/FinishPad.cs.meta
- [점프패드 구간 난이도 완화 & 최고기록 1분 55초 달성](https://github.com/SWPP-2025SPRING/team-project-for-2025-spring-swpp-team-08/commit/973cc033616960e6c937afaf9d83db8d22f60c08)
- [FinishPad 스크립트 추가 및 FinishGame 트리거 완료](https://github.com/SWPP-2025SPRING/team-project-for-2025-spring-swpp-team-08/commit/eb2e3db8f608927962edbf21e4b805660d6d0534)
- [씬 전환 완료](https://github.com/SWPP-2025SPRING/team-project-for-2025-spring-swpp-team-08/commit/2b1362d1845c579a522b4b89c140d0647ebe5390)
- FinishPad에 닿으면 씬 잘 넘어가는거 확인 완료
=> stage1 난이도 조정 및 씬 전환

Assets/Scenes/EndingScene.unity, ProjectSettings/EditorBuildSettings.asset
- 씬 정리를 했습니다
- x
- 
x
위 사진: 리팩토링 이전
=> [ETC] refactoring ending scene

Assets/Scenes/OpeningScene.unity, Assets/Scripts/Opening/HidableComponent.cs, Assets/Scripts/Opening/HidableComponent.cs.meta, Assets/Scripts/Opening/MovingComponent.cs, Assets/Scripts/Opening/MovingComponent.cs.meta, Assets/Scripts/Opening/OpeningSequence.cs
- 두가지 리팩토링을 진행했습니다.
- opening sequence에서 game object의 렌더링 옵션 등을 직접 핸들링 하는 대신, 각 object에서 핸들링하도록 역할 분리
- opening sequence의 각 파트를 구분하기 쉽게 메소드 나누기
- 기존의 형태와 결과가 같은지 확인해주시면 됩니다.
-
=> opening scene 리팩토링

Assets/DownloadedAssets/ParticleLight/Materials/Jet 2.mat, Assets/Prefabs/Commons/IngameCanvas.prefab, Assets/Scenes/OpeningScene.unity, Assets/Scripts/Managers/PlayManager.cs, Assets/Scripts/Opening/OpeningManager.cs
- conflict 풀면서 사라졌던 play manager 일부 코드 살리기 - 3a638b7857896b98f02319c51195e516198d3ae9
- opening entrance 파랑색  material로 적용(prefab엔 영향 없음) - 49b9f89751fcdb61fa1a39ba795eb440ae795c0a
- input name ui default로 가리기 - 7cdb0339bb8521f6e32742f6ec602e7e6835a9c2
- 
-
=> [ETC] 기타 수정사항

Assets/Scenes/Stage1Scene.unity
- [ui 적용](https://github.com/SWPP-2025SPRING/team-project-for-2025-spring-swpp-team-08/commit/8f9a2e85e485edba0f32fc315fe909c5e244cf04)
- [플레이어 하나 남기고 삭제](https://github.com/SWPP-2025SPRING/team-project-for-2025-spring-swpp-team-08/commit/0fedc81e72b0acc8ac5dd7d3a1290857b149c4ce)
=> Stage1 업데이트된 ui 적용

Assets/Scripts/ScoreBoard/ToMain.cs
- 게임매니저를 사용해서 씬 전환을 하도록 코드 수정
- 수정 후 에러가 안 나는지
- 다른 창에서 사용하는 코드만 고쳐두고 고쳤다고 착각하고 있었네요
=> [ETC] fixed scene transition

Assets/Prefabs/Commons/IngameCanvas.prefab, Assets/Scenes/OpeningScene.unity, Assets/Scripts/Opening/InputName.cs, Assets/Scripts/Opening/OpeningManager.cs, Assets/Scripts/Opening/OpeningSequence.cs
- OpeningScene에서 InputField를 좀 멋있게 수정했습니다.  
- 변경된 사항이 제대로 작동하는지
- 현재 실행 시 연출이 스킵되고 방 모델링이 안 없어지는데 이는 에디터 한정으로 연출을 스킵한 것입니다.
=> Modify inputfield logic and appearance

Assets/Plugins.meta, Assets/Plugins/syncfs.jslib, Assets/Plugins/syncfs.jslib.meta, Assets/Prefabs/Commons/IngameCanvas.prefab, Assets/Prefabs/Managers/PlayManager.prefab, Assets/Scenes/EndingScene.unity, Assets/Scenes/LeaderboardMyRankScene.unity, Assets/Scenes/LeaderboardScene.unity, Assets/Scripts/Commons/NewPlayerControl.cs, Assets/Scripts/Ending/ScoreBoardManager.cs, Assets/Scripts/Managers/PlayManager.cs, Assets/Scripts/Managers/UIManager.cs, Assets/Scripts/ScoreBoard/IndexedDBSync.cs, Assets/Scripts/ScoreBoard/IndexedDBSync.cs.meta, ProjectSettings/ProjectSettings.asset
- Scoreboard가 제대로 작동하지 않던 오류를 수정했습니다.
- Scoreboard가 제대로 작동하는지
- 없음
=> Fixed result scoreboard issue

Assets/Prefabs/Commons/IngameCanvas.prefab, Assets/Scenes/MainScene.unity, ProjectSettings/ProjectSettings.asset
- 게임 이름 수정
- 리절트 등수 제거 (임시)
- 게임이 제대로 플레이할 수 있는지
- 없음
=> Minor fix before first build

Assets/Scripts/Managers/PlayManager.cs, ProjectSettings/ProjectSettings.asset
- 첫번째 스테이지 이후 음악이 루프하지 않는 현상을 수정했습니다.
- 작업 내용이 잘 작동하는지
- 없음
=> Fix PlayManager bgm loop issue

Assets/Prefabs/Commons/IngameCanvas.prefab, ProjectSettings/ProjectSettings.asset
- 스테이지 시작 시 스테이지 클리어 제목 텍스트가 나타나는 현상을 수정했습니다.
- 스테이지 진입 시 스테이지 클리어 연출이 재생되지 않는지
- 없음
=> Fix result UI issue

Assets/Scenes/EndingScene.unity
- 엔딩씬 카메라 오프셋 -5 -> -7 (통일)
- 다른 씬과 같은지
- x
=> [ETC] camera
